### ISSUE TITLE
Cross Site Script Vulnerability on module "Shop" in NavigateCMS 2.9

### ISSUE THREAD

**Issue by r0ck3t1973** [NavigateCMS/Navigate-CMS#10]
**/**Describe the bug**/**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Shop" feature Navigate

**/**To Reproduce**/**

1. Login into the panel
2. Go to 'navigate/navigate.php?fid=dashboard'
3. Go to Moudle "Shop"
4. Chose:
 - Go to "/navigate/navigate.php?fid=products"
 - Go to "/navigate/navigate.php?fid=coupons"
 - Go to "/navigate/navigate.php?fid=brands"
 - Go to "/navigate/navigate.php?fid=shipping_methods"
 - Go to "/navigate/navigate.php?fid=payment_methods"
5. Click "Create" >> Insert Payload:

   '><details/open/ontoggle=confirm(1337)>

6. Save: XSS alert Message!

**/**Expected behavior**/**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**/**Impact**/**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**/**Screenshots**/**
Info NavigateCMS 2.9:
![info](https://user-images.githubusercontent.com/62001260/84908279-79264180-b0de-11ea-9e68-2f47314fd8bb.PNG)

Ex1: Chose go to: "/navigate/navigate.php?fid=products"
![product1](https://user-images.githubusercontent.com/62001260/84908403-9eb34b00-b0de-11ea-97a4-81442ed8eae5.PNG)
![2](https://user-images.githubusercontent.com/62001260/84909018-6102f200-b0df-11ea-9917-d8d3cd797071.PNG)
![3](https://user-images.githubusercontent.com/62001260/84909031-652f0f80-b0df-11ea-961b-f18c61568ad5.PNG)
Ex2: Chose go to: "/navigate/navigate.php?fid=coupons"
![4](https://user-images.githubusercontent.com/62001260/84909394-d53d9580-b0df-11ea-895e-8ebdc2ab5949.PNG)
![5](https://user-images.githubusercontent.com/62001260/84909451-e7b7cf00-b0df-11ea-9659-d461071e6d78.PNG)
Ex3: Chose go to: "Go to "/navigate/navigate.php?fid=brands"
![6](https://user-images.githubusercontent.com/62001260/84909617-1d5cb800-b0e0-11ea-9761-db20cfbe558a.PNG)
![7](https://user-images.githubusercontent.com/62001260/84909638-20f03f00-b0e0-11ea-875f-69cdf98be3d0.PNG)
Ex4: Chose go to: "/navigate/navigate.php?fid=shipping_methods"
![8](https://user-images.githubusercontent.com/62001260/84909819-5563fb00-b0e0-11ea-96ed-a999c4ef3225.PNG)
![9](https://user-images.githubusercontent.com/62001260/84909829-58f78200-b0e0-11ea-92d8-3557355df2d8.PNG)
Ex5: Chose go to: "/navigate/navigate.php?fid=payment_methods"
![10](https://user-images.githubusercontent.com/62001260/84910001-8d6b3e00-b0e0-11ea-99ac-ea1872bed9b8.PNG)
![11](https://user-images.githubusercontent.com/62001260/84910012-90fec500-b0e0-11ea-8ea1-e3dc2a8f8cec.PNG)

**/**Desktop (please complete the following information):**/**
OS: Windows
Browser: All

**_I Hope you fix it ASAP_**

**Comment by NavigateCMS** [comment]
Fixed by commit 9be89445c4dc018b16b759714b0d4ba8493fb042

**Comment by r0ck3t1973** [comment]
Hi Team Security NavigateCMS

You can a CVE ID assigne!

Thanks you!
