### ISSUE TITLE
Cross Site Script Vulnerability on module "Configuration" in NavigateCMS 2.9

### ISSUE THREAD

**Issue by r0ck3t1973** [NavigateCMS/Navigate-CMS#11]
**/Describe the bug/**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Configuration" feature Navigate

**/To Reproduce/**

1. Login into the panel
2. Go to '/navigate/navigate.php?fid=about'
3. Go to Moudle "Configuration"
4. Chose:
 - Go to "/navigate/navigate.php?fid=users"
 - Go to "/navigate/navigate.php?fid=profiles"
 - Go to "/navigate/navigate.php?fid=menus"
 - Go to "/navigate/navigate.php?fid=functions"
 - Go to "/navigate/navigate.php?fid=backups"

5. Click "Create" >> Insert Payload:

  '><details/open/ontoggle=confirm(1337)>

6. Save: XSS alert Message!

**/Expected behavior/**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**/Impact/**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**/Screenshots/**
Info NavigateCMS 2.9:
![info](https://user-images.githubusercontent.com/62001260/84911834-e76d0300-b0e2-11ea-8141-89682943eb25.PNG)

Ex1: Chose go to "/navigate/navigate.php?fid=users"
![user](https://user-images.githubusercontent.com/62001260/84912586-c6f17880-b0e3-11ea-9851-7ee45dc8e39e.PNG)
![user1](https://user-images.githubusercontent.com/62001260/84912603-c9ec6900-b0e3-11ea-83f2-4998fff406ab.PNG)
Ex2: Chose go to "/navigate/navigate.php?fid=profiles"
![profile](https://user-images.githubusercontent.com/62001260/84912828-0a4be700-b0e4-11ea-8b9d-9fbeb7727f2b.PNG)
![profile1](https://user-images.githubusercontent.com/62001260/84912841-0d46d780-b0e4-11ea-9449-d6ad40ddafb8.PNG)
Ex3: Chose go to "/navigate/navigate.php?fid=menus"
![menu](https://user-images.githubusercontent.com/62001260/84913062-4b43fb80-b0e4-11ea-87bb-d4a157b4e2d7.PNG)
![menu1](https://user-images.githubusercontent.com/62001260/84913072-4e3eec00-b0e4-11ea-8537-01adb7eb24f5.PNG)
Ex4: Chose go to "/navigate/navigate.php?fid=functions"
![fuction](https://user-images.githubusercontent.com/62001260/84913675-f9e83c00-b0e4-11ea-804e-00172edf8061.PNG)
![function1](https://user-images.githubusercontent.com/62001260/84913749-0cfb0c00-b0e5-11ea-8e9b-372ccf464412.PNG)
Ex5: Chose go to "/navigate/navigate.php?fid=backups"
![backup](https://user-images.githubusercontent.com/62001260/84914144-7aa73800-b0e5-11ea-901e-0d93cb5b9a6f.PNG)
![Backup1](https://user-images.githubusercontent.com/62001260/84914158-7ed35580-b0e5-11ea-95ef-2baf0de4cd65.PNG)

**/Desktop (please complete the following information):/**
OS: Windows
Browser: All

**_I Hope you fix it ASAP_**

**Comment by NavigateCMS** [comment]
Fixed by ed8ba30b298a28cadcf34eca1ba0a46a060d75b3

**Comment by r0ck3t1973** [comment]
Hi Team Security @NavigateCMS 

You can a CVE ID assigne!

Thanks you!
