### ISSUE TITLE
Cross Site Script Vulnerability on module "Tools" in NavigateCMS 2.9

### ISSUE THREAD

**Issue by r0ck3t1973** [NavigateCMS/Navigate-CMS#13]
**/Describe the bug/**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Tools" feature Navigate

**/To Reproduce/**

1. Login into the panel
2. Go to 'navigate/navigate.php?fid=dashboard'
3. Go to Moudle "Tools"
4. Chose:
 - Go to "/navigate/navigate.php?fid=webusers&act=create"
 - Go to "/navigate/navigate.php?fid=webusers&act=webuser_groups_list"
5. Click "Create" >> Insert Payload:

'><details/open/ontoggle=confirm(1337)>

6. Save: XSS alert Message!

**/Expected behavior/**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**/Impact/**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**/Screenshots/**
Info NavigateCMS 2.9:
![info](https://user-images.githubusercontent.com/62001260/84919975-cb6e5f00-b0ec-11ea-8cf4-f549518bd81e.PNG)

Ex1: Chose go to "/navigate/navigate.php?fid=webusers&act=create"
![web](https://user-images.githubusercontent.com/62001260/84920047-e0e38900-b0ec-11ea-9ee4-39420da2bd6b.PNG)
![web1](https://user-images.githubusercontent.com/62001260/84920129-f953a380-b0ec-11ea-9f3c-00c8fb14f194.PNG)
Ex2: Chose go to "/navigate/navigate.php?fid=webusers&act=webuser_groups_list"
![group](https://user-images.githubusercontent.com/62001260/84920335-361f9a80-b0ed-11ea-9ba5-2e94ff8dd99c.PNG)
![group1](https://user-images.githubusercontent.com/62001260/84920349-3b7ce500-b0ed-11ea-90fa-5c3296219627.PNG)

**/Desktop (please complete the following information):/**
OS: Windows
Browser: All

**_I Hope you fix it ASAP_**

**Comment by NavigateCMS** [comment]
Fixed by 68e18703cd253d7dd058db9397718a7fdf46c5af

**Comment by r0ck3t1973** [comment]
Hi Team Security @NavigateCMS 

You can a CVE ID assigne!

Thanks you!

**Comment by r0ck3t1973** [comment]
Hi Team Security @NavigateCMS 

You can a CVE ID assigne!

Thanks you!
