### ISSUE TITLE
Cross Site Script Vulnerability on module "Web" in NavigateCMS 2.9

### ISSUE THREAD

**Issue by r0ck3t1973** [NavigateCMS/Navigate-CMS#14]
**/Describe the bug/**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Web" feature Navigate

**/To Reproduce/**

1. Login into the panel
2. Go to 'navigate/navigate.php?fid=dashboard'
3. Go to Moudle "Web"
4. Chose:
 - Go to "/navigate/navigate.php?fid=templates"
 - Go to "/navigate/navigate.php?fid=webdictionary"

5. Click "Create" >> Insert Payload:

'><details/open/ontoggle=confirm(1337)>

6. Save: XSS alert Message!

**/Expected behavior/**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**/Impact/**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**/Screenshots/**
Info NavigateCMS 2.9:
![info](https://user-images.githubusercontent.com/62001260/84921185-5a2fab80-b0ee-11ea-811d-b16014226087.PNG)

Ex1: Chose go to "/navigate/navigate.php?fid=templates"
![template](https://user-images.githubusercontent.com/62001260/84921937-54869580-b0ef-11ea-92f7-1c2b4ef878b8.PNG)
![template1](https://user-images.githubusercontent.com/62001260/84921945-57818600-b0ef-11ea-9e34-56bd677f8914.PNG)

Ex2: Chose go to "/navigate/navigate.php?fid=webdictionary"
![dictionary](https://user-images.githubusercontent.com/62001260/84922947-c6131380-b0f0-11ea-9514-e06935a9399a.PNG)
![dictionary1](https://user-images.githubusercontent.com/62001260/84922964-cb705e00-b0f0-11ea-84d9-db30fd07c2fe.PNG)

**/Desktop (please complete the following information):/**
OS: Windows
Browser: All

**_I Hope you fix it ASAP_**

**Comment by NavigateCMS** [comment]
Fixed by 24d126056390e21701b4a13755e5d441b8df3ef0
and d6c221cbfcb8d75a08b29d0f6fc5d033b5c74e02

**Comment by r0ck3t1973** [comment]
Hi Team Security NavigateCMS

You can a CVE ID assigne!

Thanks you!
