### ISSUE TITLE
Cross Site Script Vulnerability on "Tools" feature in NavigateCMS 2.9

### ISSUE THREAD

**Issue by luuthehienhbit** [NavigateCMS/Navigate-CMS#16]
**Expected behaviour**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Tools" feature.
**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.
**Steps to reproduce**
 1. Log into the Admin.
 2. Go to function "Tools" 
 3. Click Web users
![image](https://user-images.githubusercontent.com/50371661/85011728-2efb9980-b18c-11ea-8a8a-92cb99c634fa.png)
 4. Perform "Create" or "Edit"
![image](https://user-images.githubusercontent.com/50371661/85011905-6a966380-b18c-11ea-9e09-3a2af0e40bba.png)
 5. Add payload in name via Personal: '><details/open/ontoggle=confirm(document.cookie)>
 6. Load web:
![image](https://user-images.githubusercontent.com/50371661/85012289-03c57a00-b18d-11ea-886e-27e0f1f09da3.png)
NavigateCMS 2.9

**Comment by NavigateCMS** [comment]
Fixed by 68e18703cd253d7dd058db9397718a7fdf46c5af

**Comment by r0ck3t1973** [comment]
Hi Team Security @NavigateCMS 

You can a CVE ID assigne!

Thanks you!
