### ISSUE TITLE
Cross Site Scripting Vulnerability on "Groups" feature in NavigateCMS 2.9

### ISSUE THREAD

**Issue by Songohan22** [NavigateCMS/Navigate-CMS#17]
**Describe the bug
An authenticated malicious user can take advantage of a Stored XSS vulnerability on "Groups" in the "Tools" feature  in NavigateCMS 2.9
**To Reproduce

1. Log into the panel.
2. Go to "/navigate/navigate/navigate.php?fid=webusers"
3. Select "Groups "
4. Click "Create" groups
5. Insert payload:
                // # "><svg/onload=prompt(/SonGohan22/)>
                "><svg/onload=alert(document.domain)>
6. Click "Save"
7. Reoad "Web Server" in the funcition "Tools"
8. View the preview to trigger XSS.
9. View the preview to get in request and such Stored XSS.

**Expected behavior
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots
![image](https://user-images.githubusercontent.com/29293812/85092698-79285d80-b214-11ea-9422-ff94fb9deb3e.png)
![image](https://user-images.githubusercontent.com/29293812/85092845-d91f0400-b214-11ea-93ca-4596b5b2e6ba.png)
![image](https://user-images.githubusercontent.com/29293812/85092895-f6ec6900-b214-11ea-8677-0801f2356f50.png)

**Desktop (please complete the following information):
- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by NavigateCMS** [comment]
Fixed by 09e85d216ac70efa917547b24418e29efc1d0f75
