### ISSUE TITLE
Cross Site Script Vulnerability NavigateCMS 2.9 

### ISSUE THREAD

**Issue by luuthehienhbit** [NavigateCMS/Navigate-CMS#18]
**Expected behaviour**
An authenticated malicious user can take advantage of a Reflected XSS vulnerability in the **name="wrong_path_redirect"** feature.
Impact
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.
**Steps to reproduce**
  1. Log into the Admin.
  2. Go to function "Web > Web sites"
  3. Click website edit.
  4. Use Burp Suite inject payload to **name="wrong_path_redirect"**:
![image](https://user-images.githubusercontent.com/50371661/85096111-84cc5200-b21d-11ea-9d77-055412721a6b.png)
   Request: http://10.14.140.69:8012/navigate/navigate/navigate.php?fid=websites&act=edit&id=3&tab=0
![image](https://user-images.githubusercontent.com/50371661/85096160-b6ddb400-b21d-11ea-8467-f75ab83d3bae.png)

**Comment by NavigateCMS** [comment]
Fixed by a5e758b490dfb58d617a76acd18c6356a6225e95
