### ISSUE TITLE
Cross Site Script Vulnerability NavigateCMS 2.9

### ISSUE THREAD

**Issue by tranvannam186** [NavigateCMS/Navigate-CMS#19]
**Expected behaviour**
An authenticated malicious user can take advantage of a Reflected XSS vulnerability in the **name=**"**Aliases**" feature.
**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.
**Steps to reproduce**
1. Log into the Admin.
2. Go to function "Web > Web sites"
3. Go to "create > Aliases > add"
4. add "// # "><svg/onload=prompt(/NamTV/)>" in textbox Alias and Real URL.
5. Click "save".

--------------result--------------
![image](https://user-images.githubusercontent.com/35331850/85097396-96aff400-b221-11ea-8f58-b9fec58ed75b.png)

**Comment by NavigateCMS** [comment]
Fixed by b1a17aebbbf567448d8aae56526dbc33a8b3fa7d
