### ISSUE TITLE
Reflected XSS attack on the Help feature in NavigateCMS 2.9

### ISSUE THREAD

**Issue by hydrasky-team** [NavigateCMS/Navigate-CMS#23]
**EXPECTED BEHAVIOUR**
An authenticated malicious user can take advantage of a Reflected XSS vulnerability in the Help feature.

**IMPACT**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**VULNERABILITY CODE**
I found the vulnerability code is in  **\lib\layout\layout.class.php**

![image](https://user-images.githubusercontent.com/64893387/122892131-54a71a00-d36f-11eb-8b0b-46a9799f3f21.png)

**STEPS TO REPRODUCE**

1.  We change the request

`GET /navigate-2.9.3r1525/navigate/navigate.php?fid=%22onmouseover%3d%22alert(%27xss%27)%22%3b%22&act=edit&id=&tab=0&tab_language=&form-sent=true&id=&date_to_display=2021-06-04+01%3a27&date_published=&date_unpublish=&access=0&permission=0&item-author=1&item-author-text=admin&association[]=category&category=&embedding[]=1&template=content`

![image](https://user-images.githubusercontent.com/64893387/122892713-d39c5280-d36f-11eb-9c7b-b4a79c436fce.png)

2. Log into your account

3. Then when people move the cursor to Help feature, the Reflected XSS is executed ( don’t need to click ).

![image](https://user-images.githubusercontent.com/64893387/122892843-f3cc1180-d36f-11eb-85b9-7862bdd000aa.png)

**Comment by NavigateCMS** [comment]
Fixed by 1dfcaa3909e797d4e5632df5a8dc38decc4bd2cf and b2937f5839f25b7c16a2533ea668c1b202e9fc0c (core.php file)

Thank you very much @hydrasky-team
