### ISSUE TITLE
Stored Cross Site Scripting (XSS) and CSRF vulnerability can be chained to achieve account takeover.

### ISSUE THREAD

**Issue by SecGus** [NavigateCMS/Navigate-CMS#7]
I have discovered multiple vulnerabilities in the application, that can be chained together to achieve a full account takeover.

**Comment by SecGus** [comment]
I tried to report it via the support link for bugs on your main page (https://bitbucket.org/navigatecms/navigatecms/issues/new), this seems to be broken, so if you are interested in more details, please reply on here.

**Comment by NavigateCMS** [comment]
Thank you for finding this issue. Do you mind sending all details via email to info@navigatecms.com?

**Comment by SecGus** [comment]
E-mail with details sent. Let me know if anything else is needed.

**Comment by NavigateCMS** [comment]
Fixed by 967da65e40efbdf31973b8f065de9eabebd3accf and other commits
